package com.harshiitx.habittickoff.domain.quotes

/**
 * ~140 short, punchy lines meant to be read in under two seconds and shove
 * you toward the gym/desk/books. A mix of traditional proverbs, short
 * public-domain-era quotations, and original tough-love/psychological-fact
 * one-liners written for this app.
 */
val QUOTES: List<String> = listOf(
    // Proverbs
    "A journey of a thousand miles begins with a single step.",
    "The best time to plant a tree was twenty years ago. The second best time is now.",
    "Fall seven times, stand up eight.",
    "A smooth sea never made a skilled sailor.",
    "Little strokes fell great oaks.",
    "The obstacle is the way.",
    "Sharpen the axe before you swing it — but swing it.",
    "A river cuts through rock not because of its power, but its persistence.",
    "He who chases two rabbits catches neither.",
    "The pot that boils over was never watched closely enough.",
    "A single arrow is easily broken. A bundle is not.",
    "Dig the well before you are thirsty.",
    "The bamboo that bends is stronger than the oak that resists.",
    "Slow and steady wins the race no one else was even running.",
    "You cannot cross the sea merely by standing and staring at the water.",
    "Better to light one candle than curse the darkness.",
    "The mountain does not move, but you can.",
    "A blunt knife requires more force, not more excuses.",
    "Water dripping day by day wears the hardest rock away.",
    "No mud, no lotus.",
    "The frog in the well knows nothing of the sea until it jumps.",
    "One who waits for a chance may wait forever.",
    "Even a small star shines in the darkness.",
    "It is not the mountain we conquer, but ourselves.",
    "Cross the river by feeling for the stones — but keep walking.",

    // Short historical / public-domain-era quotations
    "The only thing we have to fear is fear itself.",
    "Whether you think you can, or you think you can't — you're right.",
    "It always seems impossible until it is done.",
    "Do the thing and you will have the power.",
    "Discipline is the bridge between goals and accomplishment.",
    "The successful warrior is the average man with laser-like focus.",
    "A ship in harbor is safe, but that is not what ships are built for.",
    "Well done is better than well said.",
    "Energy and persistence conquer all things.",
    "What lies behind us and before us are small matters compared to what lies within us.",
    "Nothing great was ever achieved without enthusiasm.",
    "You miss one hundred percent of the shots you never take.",
    "Do not wait to strike till the iron is hot, but make it hot by striking.",
    "The man who moves a mountain begins by carrying away small stones.",
    "Genius is one percent inspiration and ninety-nine percent perspiration.",
    "It is not the load that breaks you down, it is how you carry it.",
    "Perseverance is not a long race; it is many short races one after another.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Amateurs sit and wait for inspiration. The rest of us just get up and go to work.",

    // Original tough-love / drill lines
    "Nobody is coming to save you. Get up.",
    "You already know what you have to do. Stop asking and go do it.",
    "The version of you that keeps quitting isn't the real one. Prove it.",
    "Tired is not an excuse. Tired is the point where it starts counting.",
    "Comfortable is where dreams go to die quietly.",
    "You don't need motivation. You need ten more minutes and then it's done.",
    "Every rep you skip, someone else is doing it right now.",
    "Excuses are well-rehearsed lies you tell only yourself.",
    "The gym doesn't care about your mood. Neither should you.",
    "You've talked about it enough. Talk is the cheapest thing you own.",
    "Future you is watching this exact moment. Don't embarrass them.",
    "Discomfort now is a discount on regret later.",
    "Stop negotiating with the version of you that wants to quit.",
    "Nobody remembers the day you felt like it. They remember what you built.",
    "The weight doesn't get lighter because you complained about it.",
    "You are one decision away from a completely different week.",
    "Do it scared. Do it tired. Just do it before you talk yourself out of it.",
    "The book won't read itself and the reps won't count themselves.",
    "Stop waiting to feel ready. Ready is a lie people tell to stay comfortable.",
    "Your competition is training right now while you're reading this.",
    "You don't rise to the level of your goals, you fall to the level of your habits — so fix the habits.",
    "The five minutes you almost skipped is exactly where the growth was.",
    "Quit thinking about it and put your shoes on.",
    "Nobody built anything great on a day they felt inspired. They built it anyway.",
    "One more page. One more set. One more email. That's the whole game.",
    "You're not tired, you're just uncomfortable. Those are different things.",
    "The plan was never to feel like it. The plan was to do it regardless.",
    "Every excuse you make is a vote for the person you don't want to become.",
    "Get out of your own way and let the work happen.",
    "The couch will still be there in an hour. Go now.",
    "Discipline looks boring right up until it changes your entire life.",
    "You've survived every hard day so far. This one is not special.",
    "There is no version of your goals that doesn't run through today.",
    "Stop waiting for Monday. Monday didn't ask you to wait.",
    "The only workout you regret is the one you skipped.",
    "Your future depends on what you do in the next ten minutes, not what you feel.",
    "Show up especially on the days you don't want to.",
    "The gap between who you are and who you want to be is called effort.",
    "Nobody is impressed by potential. Show the work.",
    "Do it now. Later has a terrible track record.",

    // Original hard-hitting psychological facts
    "Motivation follows action almost every time — it rarely leads it.",
    "The brain treats avoidance as a reward, which is exactly why procrastination feels so good and costs so much.",
    "Willpower is a limited resource early in the day and a habit is what survives after it runs out.",
    "You feel resistance right before the moments that change you the most — that's not a coincidence.",
    "The mind exaggerates the discomfort of starting and completely forgets it two minutes in.",
    "Regret from inaction lingers far longer in memory than regret from failure.",
    "Identity changes faster through small repeated actions than through big one-time decisions.",
    "The brain can't tell the difference between 'I don't have time' and 'I'd rather not' — but your results can.",
    "Discomfort tolerance is trainable. Every rep you push through raises your ceiling for the next one.",
    "The urge to quit peaks right before the breakthrough, then drops fast if you push past it.",
    "People overestimate what they can do in a day and wildly underestimate what a year of small days adds up to.",
    "Your brain rewards you more for planning to work than for actually working — so stop planning and start.",
    "The anxiety before starting a hard task is almost always worse than the task itself.",
    "A two-minute start is often enough to dissolve the resistance that kept you stuck for an hour.",
    "What you repeatedly do in private eventually becomes who you are in public.",

    // Original punchy "song lyric" style lines
    "Burn the boats, there's no version of this where you go back.",
    "Every scar is a receipt for a fight you didn't lose.",
    "I wasn't born ready, I just stopped waiting to be.",
    "They said slow down. I said watch me.",
    "Sweat now, so the story sounds better later.",
    "I'm not chasing perfect, I'm chasing done.",
    "The fire doesn't ask permission to burn — neither should you.",
    "Some nights the only applause is your own heartbeat. Show up anyway.",
    "I built this on the days nobody was watching.",
    "You can't edit a page you never wrote.",
    "Loud dreams need quiet mornings and a locked door.",
    "I stopped waiting for the sign — I am the sign.",
    "Every 'no' was just fuel with bad timing.",
    "The grind doesn't trend, it just works.",
    "Cut the noise, keep the fire.",

    // Original movie-dialogue style lines
    "You don't get to be tired yet. Tired comes after you've earned it.",
    "This is the part of the story where most people quit. Don't be most people.",
    "Pain is temporary, but quitting is a decision you carry forever.",
    "The only way out of this is through it — so start walking.",
    "You wanted the dream. Nobody said the dream doesn't have a price.",
    "Everyone wants the result. Almost nobody wants the process. Be the exception.",
    "You don't find out what you're made of on the easy days.",
    "Get up. The story doesn't end on the floor.",
    "One more round. That's it. Just one more.",
    "You've come too far to negotiate with the old version of yourself now.",
    "The moment you want to quit is the moment that separates everyone else from you.",
    "There's no shortcut on this map. There's just the work and the finish line.",
    "You're not going to feel ready. Go anyway.",
    "This is the hard part. Everyone said there'd be a hard part.",
    "Whatever it takes. Not whatever is convenient — whatever it takes.",

    // A few more mixed closers
    "The best apology is changed behavior. Apologize to yourself with action today.",
    "You don't need a new plan. You need to run the one you already have.",
    "Small disciplines repeated daily lead to massive results compounded over time.",
    "The only workout that doesn't count is the one you talk yourself out of.",
    "Long-term consistency beats short-term intensity, every single time.",
    "You are the only one keeping score on the days nobody else is watching — make it count.",
    "The finish line doesn't move. Your excuses do.",
    "Today's effort is a letter to the person you'll be in a year.",
    "Nobody drowns from falling in water — they drown from staying there. Get out and swim.",
    "The best moment to start was earlier. The next best moment is right now."
)
